server:
  port: 1949

guns:
  swagger-open: true              #是否开启swagger (true/false)
  kaptcha-open: false             #是否开启登录时验证码 (true/false)
#  file-upload-path: c:/tmp/tmp
  file-upload-path: /images/web-guide    #文件上传目录(不配置的话为java.io.tmpdir目录)

  #文件上传目录(不配置的话为java.io.tmpdir目录)
  spring-session-open: false      #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900  #多久检测一次失效的session(只在单机环境下生效) 单位：秒
  flag: true # 是否打开自动监控机制

beetl:
  resource-auto-check: true       #热加载beetl模板，开发时候用

spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

mybatis-plus:
  typeAliasesPackage: com.nikati.manage.modular.system.model

log:
  path: manage-logs

---

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/webstack?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 111111
   # filters: wall,mergeStat
  redis:
    database: 1
    host: 127.0.0.1
    password:
    jedis:
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 8000
    port: 6379



